[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "geoalchemy2>=0.17.1",
    "psycopg2-binary>=2.9.10",
    "sqlalchemy>=2.0.40",
]
