# config.toml This is a configuration file for Streamlit, a Python library for building web applications.
# The file is in TOML format, which is a minimal configuration file format.
# The sections are defined by square brackets, and key-value pairs are separated by an equals sign.
# The file contains settings for the Streamlit application, including theme and server settings.
# The comments (lines starting with #) explain the purpose of each section and setting.


# The file is used to customize the appearance and behavior of the Streamlit app.
[theme]
primaryColor="#E600E6" # Magenta (RGB: 230, 0, 230)
backgroundColor="#000000" # Black (RGB: 0, 0, 0)
secondaryBackgroundColor="#1E1E1E" # Dark Gray (RGB: 30, 30, 30) - Used for sidebar, widget backgrounds
textColor="#FFFFFF" # White (RGB: 255, 255, 255)
font="sans serif" # Or "serif" or "monospace"


[client]
# Optional: Caching settings
# Caching can also be managed in code via @st.cache_data / @st.cache_resource

[server]
headless = false  # Run Streamlit in headless mode (no browser) - useful for automated tasks.  Defaults to false.
port = 8501  # The port the Streamlit server listens on. Defaults to 8501.
enableCORS = true  # Enable Cross-Origin Resource Sharing (CORS). Defaults to true. Set to false to disable browser origin checks.
enableXsrfProtection = true # Enables Cross-Site Request Forgery (CSRF) protection. Defaults to true.  Disable for testing if needed.

