[theme]
primaryColor="#E600E6" # Magenta (RGB: 230, 0, 230)
backgroundColor="#000000" # Black (RGB: 0, 0, 0)
secondaryBackgroundColor="#1E1E1E" # Dark Gray (RGB: 30, 30, 30) - Used for sidebar, widget backgrounds
textColor="#FFFFFF" # White (RGB: 255, 255, 255)
font="sans serif" # Or "serif" or "monospace"

[client]
# Optional: Caching settings
# Caching can also be managed in code via @st.cache_data / @st.cache_resource

[server]
# Optional: Adjust settings if needed
# headless = true
# runOnSave = true
