
[environment]
type = "development"
debug = "true"
logging_level = "DEBUG"

[database]
host = "ep-morning-hat-a42dpm9i.us-east-1.aws.neon.tech"
port = "5432"
database = "neondb"
username = "neondb_owner"
password = "npg_v3eMnEs8pJuR"

[logging]
level = "INFO"
file_path = "logs/app.log"
enable_telemetry = "false"

[features]
enable_experimental = true
show_developer_tools = true
cache_ttl = 3600
