
[environment]
type = "development"
debug = "true"
logging_level = "DEBUG"

[database]
# Database credentials are stored in Replit Secrets tool
# as DATABASE_URL, PGDATABASE, PGHOST, PGPORT, PGUSER, PGPASSWORD

[logging]
level = "INFO"
file_path = "logs/app.log"
enable_telemetry = "false"

[features]
enable_experimental = true
show_developer_tools = true
cache_ttl = 3600
