# This is a configuration file for Streamlit, a Python library for building web applications.
# The file is in TOML format, which is a minimal configuration file format. 
# secrets.toml is used to store sensitive information like API keys, passwords, and other secrets.
# The file is in TOML format, which is a minimal configuration file format.




