
[environment]
type = "development"
debug = "true"
logging_level = "DEBUG"

[features]
enable_experimental = true
show_developer_tools = true

[theme]
primaryColor = "#E600E6"
backgroundColor = "#000000"
secondaryBackgroundColor = "#323232"
textColor = "#FFFFFF"
