
[environment]
type = "development"
debug = "true"
logging_level = "DEBUG"

[features]
enable_experimental = true
show_developer_tools = true

[theme]
primaryColor="#E600E6" # Magenta (RGB: 230, 0, 230)
backgroundColor="#000000" # Black (RGB: 0, 0, 0)
secondaryBackgroundColor="#323232" # Dark Gray (RGB: 50, 50, 50) - Used for sidebar, widget backgrounds
textColor="#FFFFFF" # White (RGB: 255, 255, 255)
font="sans serif" # Or "serif" or "monospace"

[client]
# Optional: Caching settings
# Caching can also be managed in code via @st.cache_data / @st.cache_resource